version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env 
    environment:
      - STORAGE_EMULATOR_HOST=http://gcs:4443
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - GOOGLE_CLOUD_PROJECT=my-project-id 
    depends_on:
      - pubsub
      - gcs
    volumes:
      - .:/app 

  pubsub:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: gcloud beta emulators pubsub start --project=my-project-id --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"

  gcs:
    image: fsouza/fake-gcs-server
    command: -scheme http -external-url http://localhost:4443
    ports:
      - "4443:4443"
    volumes:
      - ./gcs_data:/data